.Dd $Mdocdate: September 07 2023 $
.Dt C_ARR_GET 3
.Os
.Sh NAME
.Nm c_arr_get
.Nd retrieve an object from array
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft void *
.Fn c_arr_get "ctype_arr *p" "usize m" "usize n"
.Sh DESCRIPTION
The
.Fn c_arr_get
function returns a pointer to the object, of
.Fa n
bytes in size, at position
.Fa m
in the array
.Fa p ,
ensuring that at least
.Fa m Ns \+1
objects are initialized.
.Sh RETURN VALUES
The
.Fn c_arr_get
function returns a pointer to the requested object if success;
otherwise nil is returned and
.Va errno
is set to indicate the error.
.Sh EXAMPLES
.Bd -literal -offset indent
int *p = c_arr_get(&arr, 1, sizeof(*p));
*p = 10;
.Ed
.Sh ERRORS
The
.Fn c_arr_get
function may fail and set the external variable
.Va errno
for any of the errors specified for the library function
.Xr c_arr_ready 3 .
.Sh SEE ALSO
.Xr c_arr_data 3
