.Dd June 17, 2019
.Dt C_ARR_BYTES 3
.Os
.Sh NAME
.Nm c_arr_bytes
.Nd calculate used memory in an array
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft usize
.Fn c_arr_bytes "CArr *p"
.Sh DESCRIPTION
The
.Fn c_arr_bytes
function calculates the used memory in the array
.Fa p .
.Sh RETURN VALUES
The
.Fn c_arr_bytes
function returns the number of initialized bytes in the given array.
.Sh SEE ALSO
.Xr c_arr_avail 3 ,
.Xr c_arr_len 3 ,
.Xr c_arr_total 3
