.Dd $Mdocdate: September 07 2023 $
.Dt C_ARR_CAT 3
.Os
.Sh NAME
.Nm c_arr_cat
.Nd concatenate objects to array
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft ctype_status
.Fn c_arr_cat "ctype_arr *p" "void *v" "usize m" "usize n"
.Sh DESCRIPTION
The
.Fn c_arr_cat
function appends
.Fa m
objects, each
.Fa n
bytes in size, from the memory area
.Fa v
to the array
.Fa p .
.Sh RETURN VALUES
.Rv -std
.Sh EXAMPLES
.Bd -literal -offset indent
int num[3] = { 6, 6, 6 };
if (c_arr_cat(&arr, &xyz, C_STD_NELEM(num), sizeof(num[0])) < 0) goto fail;
.Ed
.Sh ERRORS
The
.Fn c_arr_cat
function may fail and set the external variable
.Va errno
for any of the errors specified for the library function
.Xr c_arr_ready 3 .
