.Dd $Mdocdate: September 07 2023 $
.Dt C_ARR_AVAIL 3
.Os
.Sh NAME
.Nm c_arr_avail
.Nd calculate available memory in array
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft usize
.Fn c_arr_avail "ctype_arr *p"
.Sh DESCRIPTION
The
.Fn c_arr_avail
function calculates the available memory in the array
.Fa p .
.Sh RETURN VALUES
The
.Fn c_arr_avail
function returns the number of uninitialized bytes in the given array.
.Sh EXAMPLES
.Bd -literal -offset indent
usize n = c_arr_len(&arr, sizeof(int));
c_ioq_fmt(ioq1, "Available Memory: %llu\en", n);
c_ioq_flush(ioq1);
.Ed
.Sh SEE ALSO
.Xr c_arr_bytes 3 ,
.Xr c_arr_len 3 ,
.Xr c_arr_total 3
