.Dd $Mdocdate: September 07 2023 $
.Dt C_ARR_VFMT 3
.Os
.Sh NAME
.Nm c_arr_vfmt
.Nd concatenate formatted strings in array
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft size
.Fn c_arr_vfmt "ctype_arr *p" "char *fmt" "va_list args"
.Sh DESCRIPTION
The
.Fn c_arr_vfmt
function appends a formatted string, as described in the format
.Fa fmt ,
to the array
.Fa p .
.Pp
The formatting is performed by the function
.Xr c_fmt_fmt 3 .
.Sh RETURN VALUES
The
.Fn c_arr_vfmt
function returns the number of copied bytes if successful;
otherwise the value \-1 is returned and
.Va errno
is set to indicate the error.
.Sh EXAMPLES
.Bd -literal -offset indent
char *
strfmt(char *fmt, ...)
{
	static char buf[64];
	ctype_arr arr;
	va_list ap;
	size n;

	c_arr_init(&arr, buf, sizeof(buf));

	va_start(ap, fmt);
	n = c_arr_vfmt(p, fmt, ap);
	va_end(ap);

	if (n < 0) return nil;
	return buf;
}
.Ed
.Sh ERRORS
.Bl -tag -width Er
.It Bq Er C_ERR_NOMEM
Not enough space.
.El
.Sh SEE ALSO
.Xr c_arr_fmt 3 ,
.Xr c_fmt_fmt 3
