.Dd $Mdocdate: September 07 2023 $
.Dt C_ARR_READY 3
.Os
.Sh NAME
.Nm c_arr_ready
.Nd ensure space in array
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft ctype_status
.Fn c_dyn_ready "ctype_arr *p" "usize m" "usize n"
.Sh DESCRIPTION
The
.Fn c_arr_ready
function calculates the available memory from the array
.Fa p
to check if it has available memory to hold at least
.Fa m Ns \+1
objects, each
.Fa n
bytes in size.
.Sh RETURN VALUES
.Rv -std
.Sh EXAMPLES
.Bd -literal -offset indent
int num[10];
if (c_arr_ready(&arr, 10, sizeof(int)) < 0) goto err;
c_arr_cat(&arr, &num, C_STD_NELEM(num), sizeof(num[0]));
.Ed
.Sh ERRORS
.Bl -tag -width Er
.It Bq Er C_ERR_NOMEM
Not enough space.
.It Bq Er C_ERR_OVERFLOW
Value too large to be stored in data type.
.El
