.Dd June 17, 2019
.Dt C_ARR_GET 3
.Os
.Sh NAME
.Nm c_arr_get
.Nd get data of an array
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft void *
.Fn c_arr_get "CArr *p" "usize m" "usize n"
.Sh DESCRIPTION
The
.Fn c_arr_get
function returns a pointer to the object, of
.Fa n
bytes in size, in position
.Fa m
of the array
.Fa p .
.Fn c_arr_get
ensures that at least
.Fa m Ns \+1
objects are initialized.
.Sh RETURN VALUES
On success, the
.Fn c_arr_get
function returns a pointer to the requested object;
Otherwise, nil is returned and
.Va errno
is set to indicate the error.
.Sh ERRORS
.Bl -tag -width Er
.It Bq Er ENOMEM
Not enough space.
.It Bq Er EOVERFLOW
Value too large to be stored in data type.
.Sh SEE ALSO
.Xr c_arr_data 3
