.Dd June 17, 2019
.Dt C_ARR_TOTAL 3
.Os
.Sh NAME
.Nm c_arr_total
.Nd get the buffer size of an array
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft usize
.Fn c_arr_total "CArr *p"
.Sh DESCRIPTION
The
.Fn c_arr_total
function returns the internal buffer size, in bytes, from the array
.Fa p .
.Sh RETURN VALUES
The
.Fn c_arr_total
function returns the number of allocated bytes in the given array.
.Sh SEE ALSO
.Xr c_arr_avail 3 ,
.Xr c_arr_bytes 3 ,
.Xr c_arr_len 3
