.Dd $Mdocdate: September 10 2023 $
.Dt C_DIR_READ 3
.Os
.Sh NAME
.Nm c_dir_read
.Nd traverse file hierarchy stream
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft ctype_dent *
.Fn c_dir_read "ctype_dir *p"
.Sh DESCRIPTION
The
.Fn c_dir_read
function traverses through the file hierarchy stream
.Fa p .
.Sh RETURN VALUES
The
.Fn c_dir_read
function returns a pointer to the next entry, or nil when
there are no more entries.
.Sh EXAMPLES
.Bd -literal -offset indent
ctype_dent *ep;
while (ep = c_dir_read(&dir)) {
	switch (ep->info) {
	case C_DIR_FSD:
		c_ioq_fmt(ioq1, "%s/\en", ep->path);
		break;
	case C_DIR_FSF:
		c_ioq_fmt(ioq1, "%s", ep->path);
		break;
	case C_DIR_FSSL:
		c_ioq_fmt(ioq1, "%s@", ep->path);
	}
}
.Ed
.Sh SEE ALSO
.Xr c_dir_children 3 ,
.Xr c_dir_list 3
