.Dd $Mdocdate: September 07 2023 $
.Dt C_DYN_READY 3
.Os
.Sh NAME
.Nm c_dyn_ready
.Nd ensure space in dynamic array
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft ctype_status
.Fn c_dyn_ready "ctype_arr *p" "usize m" "usize n"
.Sh DESCRIPTION
The
.Fn c_dyn_ready
function ensures that the array
.Fa p
has available memory to hold at least
.Fa m Ns \+1
objects, each
.Fa n
bytes in size. If not enough bytes are allocated,
.Fn c_dyn_ready
allocates more bytes.
.Sh RETURN VALUES
.Rv -std
.Sh EXAMPLES
.Bd -literal -offset indent
int num[10];
if (c_dyn_ready(&arr, 10, sizeof(int)) < 0) goto err;
c_arr_cat(&arr, &num, C_STD_NELEM(num), sizeof(num[0]));
.Ed
.Sh ERRORS
The
.Fn c_dyn_ready
function may fail and set the external variable
.Va errno
for any of the errors specified for the library function
.Xr c_std_alloc 3 .
.Sh SEE ALSO
.Xr c_dyn_alloc 3
