.Dd December 20, 2019
.Dt C_DYN_ALLOC 3
.Os
.Sh NAME
.Nm c_dyn_alloc
.Nd get data of a dynamic array
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft void *
.Fn c_dyn_alloc "ctype_arr *p" "usize m" "usize n"
.Sh DESCRIPTION
The
.Fn c_dyn_alloc
function returns a pointer to the object, of
.Fa n
bytes in size, in position
.Fa m
of the array
.Fa p .
.Fn c_dyn_alloc
ensures that at least
.Fa m Ns \+1
objects are initialized.
If not enough bytes are allocated,
.Fn c_dyn_alloc
allocates more bytes.
.Sh RETURN VALUES
On success, the
.Fn c_dyn_alloc
function returns a pointer to the requested object;
Otherwise, nil is returned and
.Va errno
is set to indicate the error.
.Sh ERRORS
.Bl -tag -width Er
.It Bq Er C_ENOMEM
Not enough space.
.It Bq Er C_EOVERFLOW
Value too large to be stored in data type.
.El
.Sh SEE ALSO
.Xr c_arr_data 3 ,
.Xr c_dyn_ready 3
