.Dd $Mdocdate: December 20 2019 $
.Dt C_DYN_SHRINK
.Os
.Sh NAME
.Nm c_dyn_shrink
.Nd shrink a dynamic array
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft void
.Fn c_dyn_shrink "ctype_arr *p"
.Sh DESCRIPTION
The
.Fn c_dyn_shrink
function shrinks the internal buffer of array
.Fa p
to the number of initialized bytes.
