.Dd $Mdocdate: September 07 2023 $
.Dt C_ERR_DIE 3
.Os
.Sh NAME
.Nm c_err_die
.Nd formatted error message
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft void
.Fn c_err_die "ctype_status eval" "char *fmt" "..."
.Sh DESCRIPTION
The
.Fn c_err_die
function writes the last component of the progname followed by a colon
.Pq Sq \&:
character and a space,
a formatted error message as according to the format
.Fa fmt ,
followed by a colon
.Pq Sq \&:
character and a space,
and an error message string associated with the error value
.Va errno
on the standard error output.
.Pp
The
.Fn c_err_die
function do not return, but exit with the value of the argument
.Fa eval .
.Pp
The formatting is performed by the function
.Xr c_fmt_fmt 3 .
.Sh EXAMPLES
.Bd -literal -offset indent
if (!(buf = c_std_alloc(size, sizeof(uchar))))
	c_err_die(1, nil);

if ((fd = c_nix_fdopen2(file, C_NIX_OREAD)) < 0)
	c_err_die(1, "%s", file);
.Ed
.Sh SEE ALSO
.Xr c_err_diex 3 ,
.Xr c_err_vdie 3 ,
.Xr c_err_vdiex 3 ,
.Xr c_err_vwarn 3 ,
.Xr c_err_vwarnx 3 ,
.Xr c_err_warn 3 ,
.Xr c_err_warnx 3 ,
.Xr c_fmt_fmt 3
