.Dd $Mdocdate: September 10 2023 $
.Dt C_EXC_SPAWN1 3
.Os
.Sh NAME
.Nm c_exc_spawn1
.Nd spawn process
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft ctype_id
.Fn c_exc_spawn1 "char *prog" "char **argv" "char **envp" "ctype_fd *fd" "ctype_fd to"
.Sh DESCRIPTION
The
.Fn c_exc_spawn1
function spawns a child process running the program
.Fa prog
with argument list
.Fa argv
and environment
.Fa envp .
It sets up a pipe between the parent and child, redirecting
the file descriptor
.Fa to
in the child to the write end of the pipe.
The read end of the pipe is returned in
.Fa *fd .
.Pp
The given environment is merged with
the variables previously set by the function
.Xr c_exc_setenv 3 .
.Sh RETURN VALUES
The
.Fn c_exc_spawn1
function returns the process ID of the spawned process if successful;
otherwise \-1 is returned and
.Va errno
is set to indicate the error.
.Sh SEE ALSO
.Xr c_exc_run 3 ,
.Xr c_exc_runenv 3 ,
.Xr c_exc_spawn0 3
