.Dd $Mdocdate: September 07 2023 $
.Dt C_GEN_BASENAME 3
.Os
.Sh NAME
.Nm c_gen_basename
.Nd extract the base portion of a pathname
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft char *
.Fn c_gen_basename "char *s"
.Sh DESCRIPTION
The
.Fn c_gen_basename
function searches for the last component from the pathname
.Fa s
deleting any trailing slashes
.Pq Sq / .
.Sh RETURN VALUES
The
.Fn c_gen_basename
function returns a pointer to the last component from the given pathname.
If the pathname is a nil pointer or the string empty,
a pointer to the string
.Dq \&.
is returned.
.Sh SEE ALSO
.Xr c_gen_dirname 3
