.Dd $Mdocdate$
.Dt C_HSH_INITK 3
.Os
.Sh NAME
.Nm c_hsh_initk
.Nd initialize keyed hash
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft void
.Fn c_hsh_initk "ctype_hst *p" "void *k" "usize n"
.Sh DESCRIPTION
The
.Fn c_hsh_initk
function initializes the hash structure
.Fa p
with the key
.Fa k
of
.Fa n
bytes in size.
.Sh SEE ALSO
.Xr
