.Dd $Mdocdate$
.Dt C_IOQ_FEED 3
.Os
.Sh NAME
.Nm c_ioq_feed
.Nd feed queue
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft size
.Fn c_ioq_feed "ctype_ioq *p"
.Sh DESCRIPTION
The
.Fn c_ioq_feed
function attempts to fill the input queue
.Fa p .
.Sh RETURN VALUES
The
.Fn c_ioq_feed
function returns the current data size if existent, otherwise it returns the
size of filled data. If the operation function fails \-1 is returned.
.Sh SEE ALSO
.Xr c_ioq_flush 3
