.Dd $Mdocdate$
.Dt C_IOQ_PUTFILE 3
.Os
.Sh NAME
.Nm c_ioq_putfile
.Nd queue file
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft ctype_status
.Fn c_ioq_putfile "ctype_ioq *p" "char *s"
.Sh DESCRIPTION
The
.Fn c_ioq_putfile
function reads the file
.Fa s
appending the input to the queue
.Fa p .
If the number of bytes to append exceeds the available space in the queue,
.Fn c_ioq_putfile
flushes the data until it is enough to fit.
.Sh RETURN VALUES
.Rv -std
.Sh SEE ALSO
.Xr c_ioq_fmt 3 ,
.Xr c_ioq_nput 3 ,
.Xr c_ioq_put 3 ,
.Xr c_ioq_putfd 3 ,
.Xr c_ioq_vfmt 3
