.Dd $Mdocdate: September 07 2023 $
.Dt C_MEM_EQUAL 3
.Os
.Sh NAME
.Nm c_mem_equal
.Nd compare memory areas for equality in constant time
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft int
.Fn c_mem_equal "void *v1" "usize n" "void *v2"
.Sh DESCRIPTION
The
.Fn c_mem_equal
function compares the first
.Fa n
bytes of the memory areas
.Fa v1
and
.Fa v2 .
It does the comparison in constant time to avoid timing side-channel attacks.
.Sh RETURN VALUES
The
.Fn c_mem_equal
function returns zero or not zero if the first
.Fa n
bytes of the memory areas
.Fa v1
and
.Fa v2 ,
respectively, are equal or different.
.Sh EXAMPLES
.Bd -literal -offset indent
if (c_mem_equal(buf1, sizeof(buf1), buf2)) {
	c_ioq_put(ioq1, "The bufs differ\en");
} else {
	c_ioq_put(ioq1, "The bufs are equal\en");
}
c_ioq_flush(ioq1);
.Ed
.Sh SEE ALSO
.Xr c_mem_cmp 3
