.Dd $Mdocdate: January 01 2020 $
.Dt C_MEM_CCPY 3
.Os
.Sh NAME
.Nm c_mem_ccpy
.Nd copy bytes in memory
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft void *
.Fn c_mem_ccpy "void *d" "usize n" "void *s" "int c"
.Sh DESCRIPTION
The
.Fn c_mem_ccpy
function copies bytes from memory area
.Fa s
into
.Fa d .
If the byte
.Fa c
.Pq Li uchar
occurs in the memory area
.Fa s
the copy stops. Otherwise,
.Fa n
bytes are copied.
The memory areas may overlap.
.Sh RETURN VALUES
The
.Fn c_mem_ccpy
function returns a pointer to the next byte in
.Fa d
after
.Fa c ,
or nil if
.Fa c
was not found in the first
.Fa n
bytes of
.Fa s .
.Sh SEE ALSO
.Xr c_mem_cpy 3
