.Dd $Mdocdate$
.Dt C_NIX_MKTEMP 3
.Os
.Sh NAME
.Nm c_nix_mktemp
.Nd create directory path
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft ctype_status
.Fn c_nix_mktemp "char *s" "usize n"
.Sh DESCRIPTION
The
.Fn c_nix_mktemp
function takes the filename template
.Fa s
and overwrites part of it to create a unique file.
The template may be any filename with
.Ql X Ns s
appended to  it.
.Sh RETURN VALUES
.Rv -std
.Sh ERRORS
The
.Fn c_nix_mktemp
function may fail and set the external variable
.Va errno
for any of the errors specified for the library function
.Xr c_nix_fdopen3 3 .
.Sh SEE ALSO
.Xr c_nix_mktemp 3
