.Dd $Mdocdate: September 07 2023 $
.Dt C_RAND_U32INC 3
.Os
.Sh NAME
.Nm c_rand_u32inc
.Nd deterministic pseudo-random number generator
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft u32
.Fn c_rand_u32inc "ctype_rst *p" "u32 n"
.Sh DESCRIPTION
The
.Fn c_rand_u32inc
function generates a pseudo-random number,
uniformly distributed but less than
.Fa n ,
determined from the state
.Fa p .
.Sh RETURN VALUES
The
.Fn c_rand_u32inc
function returns the generated number.
.Sh SEE ALSO
.Xr c_rand_data 3 ,
.Xr c_rand_name 3
