.Dd $Mdocdate: September 07 2023 $
.Dt C_RAND_NAMEINC 3
.Os
.Sh NAME
.Nm c_rand_nameinc
.Nd deterministic pseudo-random name generator
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft u32
.Fn c_rand_nameinc "ctype_rst *p" "char *s" "usize n"
.Sh DESCRIPTION
The
.Fn c_rand_nameinc
function fills the region
.Fa s
of
.Fa n
bytes in size with pseudo-random alphanumeric
.Pq Dq A-Za-z0-9 ,
slash
.Pq Sq \&-
and underline
.Pq Sq \&_
characters determined from the state
.Fa p .
.Pp
For the first run, a starting seed should be set with the functions
.Xr c_rand_genseed 3
or
.Xr c_rand_setseed 3 .
.Sh RETURN VALUES
The
.Fn c_rand_nameinc
function returns a pointer to
.Fa s .
.Sh SEE ALSO
.Xr c_rand_datainc 3 ,
.Xr c_rand_u32inc 3
