.Dd $Mdocdate: September 07 2023 $
.Dt C_STR_CASECMP 3
.Os
.Sh NAME
.Nm c_str_casecmp
.Nd compare strings
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft int
.Fn c_str_casecmp "char *v1" "usize n" "char *v2"
.Sh DESCRIPTION
The
.Fn c_str_casecmp
function function lexicographically compare the strings
.Fa v1
and
.Fa v2 ,
ignoring the case of the characters.
It compares at most
.Fa n
bytes.
.Sh RETURN VALUES
The
.Fn c_str_casecmp
function returns an integer less than, to match,
or to be greater than the first
.Fa n
bytes of
.Fa v1
is found, respectively, to less than, to match,
or to be greater than the first
.Fa n
bytes of
.Fa v2 .
.Sh EXAMPLES
.Bd -literal -offset indent
int ret = c_str_casecmp("--help", sizeof("--help"), *argv);
if (ret > 0) {
	c_ioq_put(ioq1, "differing char is higher\en");
} else if (ret < 0) {
	c_ioq_put(ioq1, "differing char is smaller\en");
} else {
	c_ioq_put(ioq1, "both strings are equal\en");
}
c_ioq_flush(ioq1);

.Ed
.Sh SEE ALSO
.Xr c_mem_cmp 3 ,
.Xr c_str_cmp 3
