.Dd $Mdocdate$
.Dt C_STD_CALLOC 3
.Os
.Sh NAME
.Nm c_std_calloc
.Nd allocate zeroed objects
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft void *
.Fn c_std_calloc "usize m" "usize n"
.Sh DESCRIPTION
The
.Fn c_std_calloc
function allocates a zeroed memory region to hold
.Fa m
objects, each of
.Fa n
bytes in size.
If
.Fa m
is zero, then
.Fn c_std_calloc
returns a unique pointer.
.Sh RETURN VALUES
The
.Fn c_std_calloc
function returns a pointer to the allocated memory if successful;
otherwise nil is returned and
.Va errno
is set to indicate the error.
.Sh ERRORS
.Bl -tag -width Er
.It Bq Er C_ERR_EINVAL
Non-owned memory region.
.It Bq Er C_ERR_NOMEM
Out of memory.
.It Bq Er C_ERR_OVERFLOW
Value too large to be stored in data type.
.El
.Sh SEE ALSO
.Xr c_std_alloc 3 ,
.Xr c_std_free 3 ,
.Xr c_std_realloc 3 ,
.Xr c_std_setalloc 3
