.Dd $Mdocdate: September 07 2023 $
.Dt C_STR_LEN 3
.Os
.Sh NAME
.Nm c_str_len
.Nd find length of string
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft usize
.Fn c_str_len "char *s" "usize n"
.Sh DESCRIPTION
The
.Fn c_str_len
function calculates the length of the string
.Fa s ,
up to
.Fa n
characters.
.Sh RETURN VALUES
The
.Fn c_str_len
function returns the length of the given string.
