.Dd $Mdocdate: September 07 2023 $
.Dt C_STR_CASECHR 3
.Os
.Sh NAME
.Nm c_str_casechr
.Nd locate character in a string
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft char *
.Fn c_str_casechr "char *v" "usize n" "int c"
.Sh DESCRIPTION
The
.Fn
function searches for the first occurence of the character
.Fa c
in the string
.Fa v ,
ignoring the case of the characters.
It searches at most
.Fa n
bytes.
.Sh RETURN VALUES
The
.Fn c_str_casechr
function returns a pointer to the located character or nil
if not found.
.Sh EXAMPLES
.Bd -literal -offset indent
char *p;

char path[C_LIM_PATHMAX];
/* copy path to str */
p = c_str_casechr(str, sizeof(str), '.');

char *s = "Hello, World!";
p = c_str_casechr(str, -1, "w");
.Ed
.Sh SEE ALSO
.Xr c_mem_chr 3 ,
.Xr c_mem_rchr 3 ,
.Xr c_str_caserchr 3 ,
.Xr c_str_chr 3 ,
.Xr c_str_rchr 3
