.Dd $Mdocdate: September 07 2023 $
.Dt C_STR_FMTCNT 3
.Os
.Sh NAME
.Nm c_str_fmtcnt
.Nd calculate formatted string size
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft usize
.Fn c_str_fmtcnt "char *fmt" "..."
.Sh DESCRIPTION
The
.Fn c_str_fmtcnt
function calculates the size of the formatted string that would be created
as according to the format
.Fa fmt .
.Pp
The formatting is performed by the function
.Xr c_fmt_fmt 3 .
.Sh RETURN VALUES
The
.Fn c_str_fmtcnt
function returns the size of the string that would be created
given the supplied format and arguments.
.Sh EXAMPLES
.Dl usize numlen = c_str_fmtcnt("%d", num);
.Sh SEE ALSO
.Xr c_fmt_fmt 3 ,
.Xr c_str_fmt 3 ,
.Xr c_str_vfmt 3 ,
.Xr c_str_vfmtcnt 3
