.Dd $Mdocdate: September 07 2023 $
.Dt C_TAI_U64 3
.Os
.Sh NAME
.Nm c_tai_u64
.Nd set TAI64 label
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft void
.Fn c_tai_u64 "ctype_tai *t" "u64 u"
.Sh DESCRIPTION
The
.Fn c_tai_u64
function sets the TAI64 label
.Fa t
to
.Fa u .
.Sh SEE ALSO
.Xr c_tai_now 3
