.Dd $Mdocdate: September 07 2023 $
.Dt C_TAIA_ADD 3
.Os
.Sh NAME
.Nm c_taia_add
.Nd sum TAI64NA label
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft void
.Fn c_taia_add "ctype_taia *t" "ctype_taia *u" "ctype_taia *v"
.Sh DESCRIPTION
The
.Fn c_taia_add
function calculates the sum from the TAI64NA label
.Fa u
and
.Fa v
storing the result to
.Fa t .
.Sh SEE ALSO
.Xr c_taia_sub 3
