.Dd $Mdocdate: September 07 2023 $
.Dt C_TAIA_PACK 3
.Os
.Sh NAME
.Nm c_taia_pack
.Nd convert to external TAI64NA format
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft void
.Fn c_taia_pack "char *s" "ctype_tai *t"
.Sh DESCRIPTION
The
.Fn c_taia_pack
function converts the TAI64NA label from
.Fa t
to external TAI64NA format in
.Fa s .
.Sh SEE ALSO
.Xr c_taia_unpack 3
