.Dd $Mdocdate: September 07 2023 $
.Dt C_UINT_64BIGUNPACK 3
.Os
.Sh NAME
.Nm c_uint_64bigunpack
.Nd read big-endian 64-bit integer
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft u64
.Fn c_uint_64bigunpack "char *s"
.Sh DESCRIPTION
The
.Fn c_uint_64bigunpack
function portably reads a 64-bit unsigned integer as stored on a big-endian
architecture from
.Fa s .
.Sh RETURN VALUES
The
.Fn c_uint_64bigunpack
function returns the read unsigned integer.
.Sh EXAMPLES
.Bd -literal -offset indent
char buf[sizeof(u64)];
/* fill buf with number */
u64 x = c_uint_64bigunpack(buf);
.Ed
.Sh SEE ALSO
.Xr c_uint_64unpack 3
