.Dd $Mdocdate: September 07 2023 $
.Dt C_UINT_32UNPACK 3
.Os
.Sh NAME
.Nm c_uint_32unpack
.Nd read little-endian 32-bit integer
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft u32
.Fn c_uint_32unpack "char *s"
.Sh DESCRIPTION
The
.Fn c_uint_32unpack
function portably reads a 32-bit unsigned integer as stored on a little-endian
architecture from
.Fa s .
.Sh RETURN VALUES
The
.Fn c_uint_32unpack
function returns the read unsigned integer.
.Sh EXAMPLES
.Bd -literal -offset indent
char buf[sizeof(u32)];
/* fill buf with number */
u32 x = c_uint_32unpack(buf);
.Ed
.Sh SEE ALSO
.Xr c_uint_32bigunpack 3
