.Dd $Mdocdate: September 07 2023 $
.Dt C_UTF8_ISALNUM 3
.Os
.Sh NAME
.Nm c_utf8_isalnum
.Nd alphanumeric rune test
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft int
.Fn c_utf8_isalnum "ctype_rune r"
.Sh DESCRIPTION
The
.Fn c_utf8_isalnum
function tests whether the rune
.Fa r
represents an alphanumeric character.
.Pp
Alphabetic characters are those in the Unicode categories Letter,
Lowercase Letter
.Pq Ll ,
Modifier Letter
.Pq Lm ,
Other Letter
.Pq Lo ,
Titlecase Letter
.Pq Lt ,
and Uppercase Letter
.Pq Lu .
.Pp
Numeric characters are those in the Unicode category Number
and Decimal Digit
.Pq Nd .
.Sh RETURN VALUES
The
.Fn c_utf8_isalnum
function returns non-zero if the rune tests true, and zero otherwise.
.Sh SEE ALSO
.Xr c_utf8_isalpha 3 ,
.Xr c_utf8_isdigit 3 ,
.Xr c_utf8_islower 3 ,
.Xr c_utf8_istitle 3 ,
.Xr c_utf8_isupper 3
