.Dd $Mdocdate: September 07 2023 $
.Dt C_UTF8_ISSPACE 3
.Os
.Sh NAME
.Nm c_utf8_isspace
.Nd space rune test
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft int
.Fn c_utf8_isspace "ctype_rune r"
.Sh DESCRIPTION
The
.Fn c_utf8_isspace
function tests whether the rune
.Fa r
represents a space character.
.Pp
Space characters are those in the Unicode categories Space Separator
.Pq Zs ,
Line Separator
.Pq Zl ,
and Paragraph Separator
.Pq Zp .
.Sh RETURN VALUES
The
.Fn c_utf8_isspace
function returns non-zero if the rune tests true, and zero otherwise.
.Sh SEE ALSO
.Xr c_utf8_isgraph 3
