.Dd $Mdocdate: September 07 2023 $
.Dt C_UTF8_RUNELEN 3
.Os
.Sh NAME
.Nm c_utf8_runelen
.Nd calculate conversion length
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft int
.Fn c_utf8_runelen "ctype_rune r"
.Sh DESCRIPTION
The
.Fn c_utf8_runelen
function calculates the number of bytes required to convert the rune
.Fa r
into UTF.
.Sh RETURN VALUES
The
.Fn c_utf8_runelen
function returns the length required to convert the given rune.
.Sh SEE ALSO
.Xr c_utf8_runenlen 3
