.Dd $Mdocdate: September 07 2023 $
.Dt C_UTF8_UTFLEN
.Os
.Sh NAME
.Nm c_utf8_utflen
.Nd calculate string rune length
.Sh LIBRARY
.Lb tertium
.Sh SYNOPSIS
.In tertium/cpu.h
.In tertium/std.h
.Ft usize
.Fn c_utf8_utflen "char *s"
.Sh DESCRIPTION
The
.Fn c_utf8_utflen
function calculates the number of runes that are represented by
the UTF string
.Fa s .
.Sh RETURN VALUES
The
.Fn c_utf8_utflen
function returns the found number of runes.
.Sh SEE ALSO
.Xr c_utf8_utfnlen 3
